/*
 * This file is part of Applied Energistics 2.
 * Copyright (c) 2013 - 2014, AlgorithmX2, All rights reserved.
 *
 * Applied Energistics 2 is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Applied Energistics 2 is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with Applied Energistics 2.  If not, see <http://www.gnu.org/licenses/lgpl>.
 */

package appeng.container.slot;


import net.minecraft.entity.player.EntityPlayer;
import net.minecraft.item.ItemStack;
import net.minecraftforge.items.IItemHandler;


public class SlotInaccessible extends AppEngSlot {

    private ItemStack dspStack = ItemStack.EMPTY;

    public SlotInaccessible(final IItemHandler i, final int slotIdx, final int x, final int y) {
        super(i, slotIdx, x, y);
    }

    @Override
    public boolean isItemValid(final ItemStack i) {
        return false;
    }

    @Override
    public void onSlotChanged() {
        super.onSlotChanged();
        this.dspStack = ItemStack.EMPTY;
    }

    @Override
    public boolean canTakeStack(final EntityPlayer par1EntityPlayer) {
        return false;
    }

    @Override
    public ItemStack getDisplayStack() {
        if (this.dspStack.isEmpty()) {
            final ItemStack dsp = super.getDisplayStack();
            if (!dsp.isEmpty()) {
                this.dspStack = dsp.copy();
            }
        }
        return this.dspStack;
    }
}
