/*
 * This file is part of Applied Energistics 2.
 * Copyright (c) 2013 - 2017, AlgorithmX2, All rights reserved.
 *
 * Applied Energistics 2 is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Applied Energistics 2 is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with Applied Energistics 2.  If not, see <http://www.gnu.org/licenses/lgpl>.
 */

package appeng.core.stats;

import com.google.gson.JsonObject;

import net.minecraft.advancements.criterion.ItemPredicate;
import net.minecraft.item.ItemStack;
import net.minecraft.util.JSONUtils;
import net.minecraft.util.ResourceLocation;

import appeng.core.AppEng;
import appeng.items.parts.PartItem;
import appeng.items.parts.PartType;

public class PartItemPredicate extends ItemPredicate {
    private final PartType partType;

    public PartItemPredicate(String partName) {
        this.partType = PartType.valueOf(partName.toUpperCase());
    }

    @Override
    public boolean test(ItemStack item) {
        if (item.getItem() instanceof PartItem) {
            PartItem<?> itemPart = (PartItem<?>) item.getItem();
            return itemPart.getType() == partType;
        }
        return false;
    }

    public static ItemPredicate deserialize(JsonObject jsonobject) {
        if (jsonobject.has("part")) {
            return new PartItemPredicate(JSONUtils.getString(jsonobject, "part"));
        } else {
            return ItemPredicate.ANY;
        }
    }

    public static void register() {
        ItemPredicate.register(new ResourceLocation(AppEng.MOD_ID, "part"), PartItemPredicate::deserialize);
    }
}
