/*
 * This file is part of Applied Energistics 2.
 * Copyright (c) 2013 - 2014, AlgorithmX2, All rights reserved.
 *
 * Applied Energistics 2 is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Applied Energistics 2 is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with Applied Energistics 2.  If not, see <http://www.gnu.org/licenses/lgpl>.
 */

package appeng.integration.abstraction;

import net.minecraft.block.Block;
import net.minecraft.entity.player.EntityPlayer;
import net.minecraft.item.Item;
import net.minecraft.item.ItemStack;
import net.minecraft.tileentity.TileEntity;
import net.minecraft.util.IIcon;
import net.minecraftforge.common.util.ForgeDirection;

import appeng.api.parts.IFacadePart;

public interface IBC
{

	boolean isWrench(Item eq);

	boolean canWrench(Item i, EntityPlayer p, int x, int y, int z);

	void wrenchUsed(Item i, EntityPlayer p, int x, int y, int z);

	boolean canAddItemsToPipe(TileEntity te, ItemStack is, ForgeDirection dir);

	boolean addItemsToPipe(TileEntity te, ItemStack is, ForgeDirection dir);

	boolean isFacade(ItemStack is);

	boolean isPipe(TileEntity te, ForgeDirection dir);

	void addFacade(ItemStack item);

	void registerPowerP2P();

	void registerItemP2P();

	void registerLiquidsP2P();

	IFacadePart createFacadePart(Block blk, int meta, ForgeDirection side);

	IFacadePart createFacadePart(ItemStack held, ForgeDirection side);

	ItemStack getTextureForFacade(ItemStack facade);

	IIcon getFacadeTexture();

}
